name: Backstage

# Triggered after a branch is created, a tag or a branch is pushed or a PR
on:
  create:
  push:
  pull_request:

jobs:
  npm-build:
    name: npm Build
    # If the commit message contains 'ci skip', it is not necessary to run this job
    if: contains(github.event.head_commit.message, 'ci skip') == false
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [8.x]
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, test and check licenses
      run: |
        npm install
        npm run build --if-present
        npm test
        npm run check-licenses

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage/lcov.info # Created when 'npm test' is executed
        flags: Backstage # Flags allow you to isolate coverage reports for different tests
        name: backstage # Custom name for the upload

  docker-hub:
    needs: npm-build
    name: Build and Publish image to DockerHUb
    runs-on: ubuntu-latest
    # If this is a PR, it won't run
    if: contains(github.ref, 'refs/pull/') == false
    steps:

    - name: Owner Repository
      id: get_owner
      run: |
        export OWNER=$(echo ${{ github.repository }} | cut -f1 -d"/")
        echo Current Owner is $OWNER
        echo ::set-output name=owner::$OWNER

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and Push
      uses: elgohr/Publish-Docker-Github-Action@2.16
      with:
        name: ${{ steps.get_owner.outputs.owner }}/backstage
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: DockerFile
        # Label with the built image's commit
        buildoptions: " --label commit_sha_dojot=${{ github.sha }} "
        # Whether tag will be based in the branch name or in the tag name
        tag_names: true
